name: Cross-compilation test

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        board:
            # RP2350
          # https://github.com/arduino/ArduinoCore-mbed/blob/master/boards.txt
          - fqbn: rp2040:rp2040:sparkfun_iotredboard_rp2350
          #     platforms: |
            name: rp2040:rp2040
            source-url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

            # Setup Arduino command line - install esp32 and all the libs flux needs
      - name: Arduino - Install and setup the Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Arduino - Start config file
        run: arduino-cli config init --additional-urls ${{ matrix.board.source-url}}

      - name: Arduino - Update index
        run: arduino-cli core update-index

      - name: Arduino - Install platform
        run: arduino-cli core install ${{ matrix.board.name}}

      - name: Arduino - Install libraries
        run: |
            arduino-cli config set library.enable_unsafe_install true
            arduino-cli version
            arduino-cli lib install 'PicoDVI - Adafruit Fork'

      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.board.fqbn }} examples/1bit_double_buffer --library .
        
    

